---
# We're building Rust, but will use our `glitch/*` shell scripts to handle
# toolchain setup, etc.
language: rust

install:
  - glitch/install.sh

script:
  - glitch/build.sh

after_failure:
  - cat /tmp/rust/cargo/sccache/sccache-server.log
